# Lamp functions.

# Turn on or off a single lamp.
# Stack arguments:
#       Address of lamp (-9 to 9).
#       On (1) or off (0).
# Uses L register.
LAMP		EXTEND
		QXCH	QPOP
		TCR	POP	# Lamp address.
		EXTEND
		BZMF	LAMP-NEG
		# I/O 10: 3 VEL, 4 NO ATT, 5 ALT, 6 GIMBAL LOCK, 8 TRACKER, 9 PROG
		TS	TEMP-VAR
		TCR	POP	# State
		EXTEND
		BZF	LAMP10X
		CA	TEMP-VAR
		EXTEND
		WOR	010
		TCF	LAMPEND
LAMP10X		CA	TEMP-VAR
		COM
		EXTEND
		WAND	010
		TCF	LAMPEND

LAMP-NEG	# Negative lamp addresses go to I/O 163 or 11.
		COM
		# Boolean: lamp '>=' 8
		TS	TEMP-VAR
		CA	NUM8
		TS	L
		CA	TEMP-VAR
		EXTEND
		SU	Q
		EXTEND
		BZF	LAMP-11
		# I/O 163: -8 RESTART, -9 STBY
		TCR	POP	# state
		EXTEND
		BZF	LAMP163X
		CA	TEMP-VAR
		EXTEND
		WOR	0163
		TCF	LAMPEND
LAMP163X	CA	TEMP-VAR
		COM
		EXTEND
		WAND	0163
		TCF	LAMPEND

LAMP-11		# I/O 11: -2 COMP ACTY, -3 COMP ACTY, -4 TEMP, -5 KEY REL, -7 OPR ERR
		TCR	POP	# state
		EXTEND
		BZF	LAMP11X
		CA	L
		EXTEND
		WOR	011
		TCF	LAMPEND
LAMP11X		CA L
		COM
		EXTEND
		WAND	011
		#TCF	LAMPEND

LAMPEND		EXTEND
		QXCH	QPOP
		RETURN
